---
title: "Log"
author: "Teofil Nakov"
date: "03/04/2015"
output: 
  html_document:
    toc: yes
    toc_depth: 6
---

### 2015-04-20
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. cryptica tubes:
  - Measurements (KN)

### 2015-04-19
#### C. wallercreekii tubes:
  - Measurements (TN)
  - Transfer AF (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)
  - Transfer T (TN)
  
### 2015-04-18
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)

### 2015-04-17
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. cryptica tubes:
  - Measurements (KN)

### 2015-04-16
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)
  
### 2015-04-15
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. cryptica tubes:
  - Measurements (KN)

### 2015-04-14
#### C. wallercreekii tubes:
  - Measurements (YL)
  - Transfer AE (TN)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Transfer S (TN)
  
### 2015-04-13
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)

### 2015-04-12
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)

### 2015-04-11
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)
  
### 2015-04-10
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. cryptica tubes:
  - Measurements (KN)

### 2015-04-09
#### C. wallercreekii tubes:
  - Measurements (YL)
  - Transfer AD (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Transfer R (TN)
  
### 2015-04-08
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)
  - Slides (TN)
  - Microscopy (WG)

### 2015-04-07
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)

### 2015-04-06
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)
  - Microscopy (WG)

### 2015-04-05
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)
  - Slides (TN)

### 2015-04-04
#### C. wallercreekii tubes:
  - Measurements (YL)
  - Transfer AC (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Transfer Q (YL)
  - Slides (TN)

### 2015-04-03
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. cryptica tubes:
  - Measurements (KN)
  - Slides (TN)

### 2015-04-02
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Slides (YL)
  
### 2015-04-01
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN)
  - Microscopy (WG)
  
### 2015-03-31
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Microscopy (WG; TN)
  
### 2015-03-30
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  - Transfer AB (TN)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)
  - Transfer P (TN)
  - Microscopy (WG)

### 2015-03-29
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements - did not happen. Was in the field (TN)

### 2015-03-28
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)

### 2015-03-27
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)

### 2015-03-26
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)

### 2015-03-25
#### C. wallercreekii tubes:
  - Measurements (TN)
  - Transfer AA (done with the alphabet) (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)

### 2015-03-24
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes & flasks:
  - Measurements (TN)
  - Stopped measuring flasks. RNA and RINs look fine.

### 2015-03-23
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes & flasks:
  - Measurements (TN)
  - Transfer O

### 2015-03-22
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes & flasks:
  - Measurements. Flasks were not measured. `NA` added. (TN) 
  - Normally this would be a transfer day. But I decided not to transfer today in effort to space out the transfers.
  
### 2015-03-21
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes & flasks:
  - Measurements (TN)
  - RNA extraction for subjects with low RINs in previous attempt:
    - 331 @ 2
    - 333 @ 2
      - protocol as before, except 1 min instead of 1.5 min bead beating
      
### 2015-03-20
#### C. wallercreekii tubes:
  - Measurements (YL, KN)
  - Transfer Z (KN; TN)
  
#### C. cryptica tubes & flasks:
  - Measurements (YL; KN)

### 2015-03-19
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes & flasks:
  - Measurements (YL; TN)

### 2015-03-18
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. cryptica tubes & flasks:
  - Measurements (KN; TN)

### 2015-03-17
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Transfer N (TN)
    - Manually edited value for tube #2 that wasn't transferred (RF too low) (TN)

#### C. cryptica flasks:
  - Inoculated flasks for:
    - 331 @ 2ppt
    - 333 @ 2ppt
  - These had low RINs and bad looking profiles. Try to get better RNA
  
### 2015-03-16
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)

### 2015-03-15
#### C. wallercreekii tubes:
  - Measurements (TN)
  - Transfer Y (TN)
  
#### C. cryptica tubes:
  - Measurements (TH)

### 2015-03-14
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. cryptica tubes:
  - Measurements (YL)

### 2015-03-13
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)

### 2015-03-12
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)
  - Transfer M (KN; YL)
  
### 2015-03-11
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)

### 2015-03-10
#### C. wallercreekii tubes:
  - Measurements (YL)
  - Transfer X (YL; TN)
  
#### C. cryptica tubes:
  - Measurements (YL)

### 2015-03-09
#### C. wallercreekii tubes:
  - Measurements (KN; YL)
  
#### C. wallercreekii flasks:
  - One of interest 156-4 @ 36 is growing _very slowly_
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (KN; YL)

### 2015-03-08
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. wallercreekii flasks:
  - One of interest 156-4 @ 36 is growing _very slowly_
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (TN)
  
* * * * *

### 2015-03-07
#### C. wallercreekii tubes:
  - Measurements (TN)
  
#### C. wallercreekii flasks:
  - Two flasks left
  - One of interest 156-4 @ 36 is growing _very slowly_
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (YL)
  - Transfer L: down to 200 RFU (YL)
  
#### C. cryptica flasks:
  - Measurements (TN)
  - RNA extraction (total=5): (TN)
      - 331 @ 0, 36
      - 332 @ 0, 36
      - 333 @ 36
    - Some of these < 10K RFU, so lower RNA concentration is expected
  
* * * * *

### 2015-03-06
#### C. wallercreekii tubes:
  - Measurements (KN)
  
#### C. wallercreekii flasks:
  - Two flasks left
  - One of interest 156-4 @ 36 is growing _very slowly_
  - Measurements (TN)
  
#### C. cryptica tubes:
  - Measurements (KN)
  
#### C. cryptica flasks:
  - Filter holders arrived 
  - Measurements 1 hour early to start RNA extraction earlier (TN)
  - Cultures look denser. Golden brown tinge. A bit of lawn in densest culture.
  - RNA extraction batch 1 (total=10): (TN)
      - 331 @ 2, 12, 24
      - 332 @ 2, 12, 24
      - 333 @ 2, 12
      - 1263 @ 2, 12
    - Filtering works OK. A bit tedious.
    - Concentrations high in comparison. Due to much denser cultures
    - Two RNA preps with concentration too high for Qubit HS assay. Need to measure dillutions.
  - RNA extraction batch 2 (total=5): (TN)
      - 333 @ 0, 24
      - 1263 @ 0, 24, 36
        - Extracted all that had RF > 10000
        
* * * * * 

### 2015-03-05
#### C. wallercreekii tubes:
  - Measurements (YL)
  
#### C. wallercreekii flasks:
  - Measurements (TN)
  - Some cultures wonky (as before). 
  - RNA extraction for:
      - 164-11 @ 2 - fine
      - 164-11 @ 12 - fine
      - 164-11 @ 36 - small pellet given density
      - 169-30 @ 24 - wouldn't pellet. No extraction.
  
#### C. cryptica tubes:
  - Measurements (YL)
  
#### C. cryptica flasks:
  - Measurements (TN)
  - Cultures look good. Starting to get dense. No filters yet, though. Wait another day before RNA extraction and/or transfer.
  
* * * * * 
### 2015-03-04
#### C. wallercreekii tubes:
  - Measurements (KN)
  - Inoculated tubes for transfer W (KN)
  - Reduced experiment to single replicate. Transferred replicate 1 with starting RF = 200. Preserved other replicates. (TN)
  
#### C. wallercreekii flasks:
  - Measurements (TN)
  - Decided not to extract RNA. Some growth curves look wonky. Cultures are also sparse, could use a couple more days before extracting. (TN)
  
#### C. cryptica tubes:
  - Measurements (KN)
  
#### C. cryptica flasks:
  - Measurements (TN)
  - No RNA extraction today. Some cultures are ready but delay due to filter holders. (TN)

* * * * * 
